### PR TITLE
Change Hijack button from GET to POST

### PR DESCRIPTION
**Pull request by nsaje**
Hey,

I did a quick change in my fork to use POST instead of GET in admin, thereby avoiding the CSRF risks you mention in the README.

If I'm missing anything obvious why it should not be done this way, please let me know.

### CODE REVIEW

**Comment by nsaje** [comment]
I see you're still supporting Python2, can add that as well if you deem the approach OK and merge-worthy.

**Comment by JonHerr** [comment]
This code is safe and using a form post with csrf would be more secure.

**Comment by nsaje** [comment]
hey @jvamvas mind taking a look at this? I notice that you're assigned to #7 that this PR fixes

**Comment by nsaje** [comment]
hey @philippeowagner, did you have a chance to check this out?

**Comment by carlosnasillo** [comment]
@nsaje looks like a good fix, nice work. 
@philippeowagner, bumping this up. Hopefully it gets merged.

**Pull request closed without merging**
